import kotlinx.css.Color

object DeezerColors {
    val mainOrange = listOf(Color("#DC4C11"), Color("#FEAB2E"))
    val mainOrangeToPink = listOf(Color("#FEAB2E"), Color("#D81B6"))
    val mainPink = listOf(Color("#D81B60"), Color("#F06262"))
    val mainPinkToPurple = listOf(Color("#F06262"), Color("#6B42B4"))
    val mainPurple = listOf(Color("#6B42B4"), Color("#943AAB"))

    val mainFlatBlack = Color("#26303C")
    val mainFlatGrey = Color("#72727D")
    val mainFlatLightGrey = Color("#EAEAEA")
    val mainFlatOrange = Color("#FEAA2D")
    val mainFlatPink = Color("#EF5466")
    val mainFlatPurple = Color("#963CAA")

    val multicolorRed = listOf(Color("#B12525"), Color("#EF4F4F"))
    val multicolorDeepOrange = listOf(Color("#D32F2F"), Color("#F6693C"))
    val multicolorOrange = listOf(Color("#DC4C11"), Color("#FEAB2E"))
    val multicolorYellow = listOf(Color("#FFC92A"), Color("#F5E447"))
    val multicolorGreen = listOf(Color("#3CA564"), Color("#A6CE50"))
    val multicolorTeal = listOf(Color("#00796B"), Color("#00ACC1"))
    val multicolorBlue = listOf(Color("#3769C8"), Color("#11A8CC"))
    val multicolorIndigo = listOf(Color("#3A489F"), Color("#6E44B7"))
    val multicolorDeepPurple = listOf(Color("#6B42B4"), Color("#943AAB"))
    val multicolorPurple = listOf(Color("#9136A9"), Color("#D84EB6"))
    val multicolorPink = listOf(Color("#D81B60"), Color("#F06262"))
    val multicolorBlack = listOf(Color("#202122"), Color("#26303C"))

    val multicolorFlatRed = Color("#F04646")
    val multicolorFlatDeepOrange = Color("#F5693C")
    val multicolorFlatOrange = Color("#FEAA2D")
    val multicolorFlatYellow = Color("#F5E446")
    val multicolorFlatGreen = Color("#A5CD50")
    val multicolorFlatDarkGreen = Color("#3CA564")
    val multicolorFlatTeal = Color("#009BAA")
    val multicolorFlatLightBlue = Color("#2D96C8")
    val multicolorFlatBlue = Color("#3769C8")
    val multicolorFLatDeepPurple = Color("#6E46B9")
    val multicolorFlatPurple = Color("#963CAA")
    val multicolorFlatPink = Color("#EF5466")
}
